apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.vendor }}-{{ .Values.application }}-secret
  labels:
    vendor: {{ .Values.vendor }}
    tool: {{ .Values.application }}
    version: {{ .Values.version }}
data:
  administrator-login: {{ .Values.Login | b64enc | quote }}
  {{ if .Values.Password }}
  administrator-password: {{ .Values.Password | b64enc | quote }}
  {{ else }}
  administrator-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}